# Generated by Django 5.0.14 on 2026-06-23 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="presence",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "User Presence",
                "verbose_name_plural": "User Presences",
                "indexes": [
                    models.Index(
                        fields=["is_online", "-last_seen"],
                        name="presence_us_is_onli_85a98b_idx",
                    )
                ],
            },
        ),
    ]
