# Generated by Django 5.0.14 on 2026-06-22 19:25

import apps.marketplace.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("marketplace", "Marketplace"),
                            ("wallet", "Wallet"),
                            ("recordings", "Recordings"),
                        ],
                        default="portal",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("notification", "Notification"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["channel", "slug"],
            },
        ),
        migrations.CreateModel(
            name="DynamicSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(db_index=True, default="general", max_length=100),
                ),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                            ("url", "URL"),
                            ("markdown", "Markdown"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("text_value", models.TextField(blank=True)),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("bool_value", models.BooleanField(default=False)),
                ("json_value", models.JSONField(blank=True, default=dict)),
                ("default_text", models.TextField(blank=True)),
                ("default_json", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["group", "key"],
                "indexes": [
                    models.Index(
                        fields=["group", "key"], name="marketplace_group_1d1d64_idx"
                    ),
                    models.Index(
                        fields=["is_public", "is_editable"],
                        name="marketplace_is_publ_828e6b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=32, unique=True
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=150)),
                ("title", models.CharField(max_length=250)),
                ("subtitle", models.CharField(blank=True, max_length=250)),
                ("featured_job", models.BooleanField(default=False)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                ("full_description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("skills_required", models.JSONField(blank=True, default=list)),
                (
                    "age_restriction_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "age_restriction_max",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("country_restriction", models.JSONField(blank=True, default=list)),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("language_restriction", models.JSONField(blank=True, default=list)),
                (
                    "experience_requirement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("device_requirement", models.CharField(blank=True, max_length=255)),
                (
                    "payment_model",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("per_minute", "Per Minute"),
                            ("per_hour", "Per Hour"),
                            ("per_task", "Per Task"),
                            ("per_submission", "Per Submission"),
                            ("dynamic_formula", "Dynamic Formula"),
                        ],
                        default="fixed",
                        max_length=30,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=5)),
                (
                    "fixed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_hour_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_task_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_submission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dynamic_formula", models.CharField(blank=True, max_length=255)),
                ("daily_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("weekly_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("monthly_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("global_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("user_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("file_upload", "File Upload"),
                            ("text_submission", "Text Submission"),
                            ("audio_upload", "Audio Upload"),
                            ("video_upload", "Video Upload"),
                            ("image_upload", "Image Upload"),
                            ("form_submission", "Form Submission"),
                            ("google_form", "Google Form Completion"),
                            ("external_api", "External API Validation"),
                        ],
                        default="text_submission",
                        max_length=30,
                    ),
                ),
                (
                    "tutorial_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                ("tutorial_video_url", models.URLField(blank=True)),
                ("youtube_video_url", models.URLField(blank=True)),
                ("loom_video_url", models.URLField(blank=True)),
                ("external_links", models.JSONField(blank=True, default=list)),
                ("google_form_link", models.URLField(blank=True)),
                ("google_sheet_link", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                (
                    "instruction_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                ("field_schema", models.JSONField(blank=True, default=list)),
                ("payment_settings", models.JSONField(blank=True, default=dict)),
                ("limit_rules", models.JSONField(blank=True, default=dict)),
                ("submission_rules", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/jobs/banners/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/jobs/thumbnails/"
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "response_sla_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("zip", "ZIP"),
                            ("video", "Video"),
                            ("link", "Link"),
                            ("instruction", "Instruction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.job_media_upload_path,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="marketplace.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("assigned", "Assigned"),
                            ("submitted", "Submitted"),
                            ("verification", "Verification"),
                            ("payment_approved", "Payment Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=30,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "expected_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("submission_note", models.TextField(blank=True)),
                ("verification_note", models.TextField(blank=True)),
                ("workflow_payload", models.JSONField(blank=True, default=dict)),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "creator_payout_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("payment_approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="marketplace.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("file_upload", "File Upload"),
                            ("text_submission", "Text Submission"),
                            ("audio_upload", "Audio Upload"),
                            ("video_upload", "Video Upload"),
                            ("image_upload", "Image Upload"),
                            ("form_submission", "Form Submission"),
                            ("google_form", "Google Form Completion"),
                            ("external_api", "External API Validation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text_content", models.TextField(blank=True)),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                (
                    "audio_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                (
                    "video_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                (
                    "image_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.marketplace.models.marketplace_upload_path,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("form_payload", models.JSONField(blank=True, default=dict)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_revision", "Needs Revision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="marketplace.jobapplication",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_job_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "task_mode",
                    models.CharField(
                        choices=[
                            ("voice_recording", "Voice Recording"),
                            ("survey", "Survey"),
                            ("data_collection", "Data Collection"),
                            ("data_annotation", "Data Annotation"),
                            ("image_labeling", "Image Labeling"),
                            ("video_recording", "Video Recording"),
                            ("audio_validation", "Audio Validation"),
                            ("ai_training", "AI Training"),
                            ("transcription", "Transcription"),
                            ("translation", "Translation"),
                            ("content_writing", "Content Writing"),
                            ("app_testing", "App Testing"),
                            ("website_testing", "Website Testing"),
                            ("product_research", "Product Research"),
                            ("lead_generation", "Lead Generation"),
                            ("web_scraping", "Web Scraping"),
                            ("seo_tasks", "SEO Tasks"),
                            ("social_media_tasks", "Social Media Tasks"),
                            ("mobile_app_tasks", "Mobile App Tasks"),
                            ("manual_review_tasks", "Manual Review Tasks"),
                        ],
                        default="voice_recording",
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=80)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/categories/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="marketplace.marketplacecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="jobposting",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="marketplace.marketplacecategory",
            ),
        ),
        migrations.CreateModel(
            name="MarketplaceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("worker", "Worker"),
                            ("recruiter", "Recruiter"),
                            ("both", "Both"),
                        ],
                        default="worker",
                        max_length=20,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("website_url", models.URLField(blank=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("bio", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("portfolio", models.JSONField(blank=True, default=list)),
                ("work_history", models.JSONField(blank=True, default=list)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="marketplace/resumes/"
                    ),
                ),
                ("xp_points", models.PositiveIntegerField(default=0)),
                ("achievement_badges", models.JSONField(blank=True, default=list)),
                ("daily_reward_streak", models.PositiveIntegerField(default=0)),
                ("last_reward_date", models.DateField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Profile",
                "verbose_name_plural": "Marketplace Profiles",
            },
        ),
        migrations.CreateModel(
            name="RecruiterFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_recruiters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="marketplace.jobposting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="marketplace.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "job")},
            },
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="marketplace_job_id_7b65df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applicant", "-created_at"],
                name="marketplace_applica_dbc78f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "applicant")},
        ),
        migrations.AddIndex(
            model_name="jobsubmission",
            index=models.Index(
                fields=["application", "-created_at"],
                name="marketplace_applica_04b6c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobsubmission",
            index=models.Index(
                fields=["verification_status", "payment_status"],
                name="marketplace_verific_ef4ad5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacecategory",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="marketplace_is_acti_6c2f1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacecategory",
            index=models.Index(
                fields=["task_mode"], name="marketplace_task_mo_1baede_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["status", "featured_job", "-created_at"],
                name="marketplace_status_246e31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["recruiter", "-created_at"],
                name="marketplace_recruit_349928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["category", "status"], name="marketplace_categor_9e57e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recruiterfollow",
            unique_together={("user", "recruiter")},
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("user", "job")},
        ),
    ]
