# Generated by Django 5.0.14 on 2026-06-23 20:14

import apps.recordings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "sample_rate",
                    models.CharField(
                        choices=[
                            ("16kHz", "16kHz / 16-bit"),
                            ("48kHz", "48kHz / 16-bit"),
                        ],
                        default="48kHz",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "channel_a_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.recordings.models.recording_file_path,
                    ),
                ),
                (
                    "channel_b_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.recordings.models.recording_file_path,
                    ),
                ),
                (
                    "mixed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.recordings.models.recording_file_path,
                    ),
                ),
                ("file_format", models.CharField(default="wav", max_length=10)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("signal_to_noise", models.FloatField(blank=True, null=True)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("drive_link", models.URLField(blank=True)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Upload Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upload_attempts", models.IntegerField(default=0)),
                ("last_upload_attempt", models.DateTimeField(blank=True, null=True)),
                ("earnings_calculated", models.BooleanField(default=False)),
                (
                    "earnings_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_minute_rate_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("room_name", models.CharField(blank=True, max_length=100)),
                (
                    "user_a",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recording Session",
                "verbose_name_plural": "Recording Sessions",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RecordingChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("a", "Channel A"), ("b", "Channel B")], max_length=1
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("file", models.FileField(upload_to="chunks/")),
                ("duration_seconds", models.FloatField(default=0)),
                ("is_uploaded", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="recordings.recordingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="WebRTCSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("offer", "SDP Offer"),
                            ("answer", "SDP Answer"),
                            ("ice_candidate", "ICE Candidate"),
                            ("hang_up", "Hang Up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="recordings.recordingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebRTC Signal",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recordingsession",
            index=models.Index(
                fields=["user_a", "-requested_at"],
                name="recordings__user_a__353835_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordingsession",
            index=models.Index(
                fields=["user_b", "-requested_at"],
                name="recordings__user_b__bb281f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordingsession",
            index=models.Index(fields=["status"], name="recordings__status_8e15d2_idx"),
        ),
        migrations.AddIndex(
            model_name="recordingsession",
            index=models.Index(
                fields=["upload_status"], name="recordings__upload__d5bb82_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordingchunk",
            unique_together={("session", "channel", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="webrtcsignal",
            index=models.Index(
                fields=["session", "signal_type"], name="recordings__session_07c2ee_idx"
            ),
        ),
    ]
