# Generated by Django 5.0.6 on 2026-06-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_fix_json_defaults'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_sessions', to='marketplace.jobapplication'),
        ),
    ]
