# Generated by Django 5.0.14 on 2026-06-23 20:13

import apps.support.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_ticket_sla"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketreply",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Ticket Reply",
                "verbose_name_plural": "Ticket Replies",
            },
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.support.models.reply_attachment_path,
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["user", "-created_at"], name="support_sup_user_id_7a4186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "priority"], name="support_sup_status_c67c70_idx"
            ),
        ),
    ]
