# Generated by Django 5.0.14 on 2026-06-23 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordings", "__first__"),
        ("wallet", "0002_wallet_upgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonuscampaign",
            options={
                "verbose_name": "Bonus Campaign",
                "verbose_name_plural": "Bonus Campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="earningrate",
            options={
                "verbose_name": "Earning Rate",
                "verbose_name_plural": "Earning Rates",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Wallet", "verbose_name_plural": "Wallets"},
        ),
        migrations.AlterModelOptions(
            name="withdrawal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Withdrawal",
                "verbose_name_plural": "Withdrawals",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("recording_income", "Recording Income"),
                    ("task_income", "Task Income"),
                    ("bonus", "Bonus"),
                    ("referral", "Referral Bonus"),
                    ("referral_bonus", "Referral Bonus"),
                    ("admin_bonus", "Admin Bonus"),
                    ("recharge", "Recharge"),
                    ("withdrawal", "Withdrawal"),
                    ("penalty", "Penalty"),
                    ("adjustment", "Admin Adjustment"),
                    ("refund", "Refund"),
                    ("daily_reward", "Daily Reward"),
                    ("challenge", "Challenge Reward"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("upi", "UPI"),
                    ("paytm", "Paytm"),
                    ("phonepe", "PhonePe"),
                    ("google_pay", "Google Pay"),
                    ("razorpay_payout", "Razorpay Payout"),
                    ("cashfree_payout", "Cashfree Payout"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="rechargeorder",
            index=models.Index(
                fields=["user", "-created_at"], name="wallet_rech_user_id_ab43aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rechargeorder",
            index=models.Index(fields=["status"], name="wallet_rech_status_7332e0_idx"),
        ),
        migrations.AddIndex(
            model_name="rechargeplan",
            index=models.Index(
                fields=["operator", "circle", "is_active"],
                name="wallet_rech_operato_0f7563_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="wallet_tran_wallet__abbc5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="wallet_tran_transac_7debff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["user", "-created_at"], name="wallet_with_user_id_1a2d32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["status"], name="wallet_with_status_e9e494_idx"),
        ),
    ]
