# Generated by Django 5.0.14 on 2026-06-23 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("recording_request", "Recording Request"),
                            ("recording_accepted", "Recording Accepted"),
                            ("recording_rejected", "Recording Rejected"),
                            ("recording_completed", "Recording Completed"),
                            ("earnings_credited", "Earnings Credited"),
                            ("withdrawal_approved", "Withdrawal Approved"),
                            ("withdrawal_rejected", "Withdrawal Rejected"),
                            ("withdrawal_paid", "Withdrawal Paid"),
                            ("ticket_reply", "Ticket Reply"),
                            ("ticket_resolved", "Ticket Resolved"),
                            ("achievement_earned", "Achievement Earned"),
                            ("rating_received", "Rating Received"),
                            ("system", "System Notification"),
                            ("warning", "Warning"),
                            ("referral_bonus", "Referral Bonus"),
                            ("daily_reward", "Daily Reward"),
                            ("challenge_completed", "Challenge Completed"),
                            ("kyc_approved", "KYC Approved"),
                            ("kyc_rejected", "KYC Rejected"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    )
                ],
            },
        ),
    ]
